fix windows event sink log compilation error with UNICODE preprocessor
gabime/spdlog pull request #1760
Opened 2020-12-13 08:48 UTC by iko1

2020-12-13 17:38 UTC, gabime commented
You got me confused. I see you removed the ```#ifdef SPDLOG_WCHAR_TO_UTF8_SUPPORT```
 So what's the purpose of this pr ?

2020-12-14 06:09 UTC, iko1 commented
I updated this PR. I'm using #ifdef to check if `SPDLOG_WCHAR_TO_UTF8_SUPPORT` and then convert the message accordingly before calling to UNICODE version of `ReportEvent`.

2020-12-14 10:29 UTC, gabime commented on include/spdlog/sinks/win_eventlog_sink.h
> +        auto buf = std::wstring_convert<std::codecvt_utf8<wchar_t>>().from_bytes(formatted.data());
```std::wstring_convert<std::codecvt_utf8>``` is deprecated. Please use  ```details::os::wstr_to_utf8buf(..)``` instead. See usage example [here](https://github.com/gabime/spdlog/blob/9ce39a470fa7adc8b101fdd5e4325e6c371f675c/include/spdlog/logger.h#L243).

2020-12-16 00:30 UTC, gabime requested changes

2020-12-16 00:30 UTC, gabime commented on include/spdlog/details/os-inl.h
> +}
wrong error message in exception. should be “ MultiByteToWideChar”

2020-12-16 09:41 UTC, merged