bin_to_hex.h: include spdlog.h
gabime/spdlog pull request #2035
Opened 2021-08-06 22:56 UTC by dmerkushov

to support inclusion of `bin_to_hex.h` in any order with `spdlog.h`

Used to be:
Some projects require sorting inclusions in alphabetical order. But in case one includes `spdlog/fmt/bin_to_hex.h` first, then `spdlog/spdlog.h`, multiple compile errors happen:
```
bin_to_hex.h:35:45: error: ‘size_t’ has not been declared
...
bin_to_hex.h:59:42: error: ‘begin’ is not a member of ‘std’
...
bin_to_hex.h:59:65: error: ‘end’ is not a member of ‘std’
```

This PR fixes `bin_to_hex.h` so it can be included in any order with `spdlog.h`

2021-08-07 03:59 UTC, gabime commented
Thanks. I think including common.h is sufficiant..

2021-08-09 14:28 UTC, gabime requested changes
please add common.h instead spdlog.h

2021-08-09 16:48 UTC, dmerkushov commented
> please add common.h instead spdlog.h

Done

2021-08-09 17:04 UTC, merged

2021-08-09 17:04 UTC, gabime commented
Thanks @dmerkushov