Now only getting time if pattern_formatter needs it
gabime/spdlog pull request #2246
Opened 2022-01-14 02:37 UTC by doug1234

The pattern_formatter class was making unwanted calls to localtime_r or similar functions even when it didn't use the time information.  A flag was added which disables the calls when the pattern formatter is not going to use the information.

2022-01-14 23:32 UTC, gabime commented
Thanks. Not sure if it worth it considering the fact that vast majority of use cases need time and that it is cached each second. Whats the use case that make it worth the extra complxity?
Also this doesn't pass the tests (the second patter_formatter overload, the one without te pattern, needs to set the flag to true since it uses the default formatter).

2022-01-15 02:55 UTC, doug1234 commented
Fixed the incorrect initialization.  Sorry about that.

Thanks for looking over the pull request.  I actually didn't add it for efficiency reasons.  I was making some spdlog calls between a fork() and execv().  There was a random crash that was in localtime_r().  It seems that localtime_r() needs to do some stuff with environment variables and likely that wasn't a safe time to check environment variables.  So I modified my pattern so as to not have time and was shocked to find it randomly crashing in the same place!  After my change the random crashes went away.

2022-01-15 15:48 UTC, doug1234 commented
If you take a look at the fork() man page (https://man7.org/linux/man-pages/man2/fork.2.html), calling a lot of functions is unsafe between fork() and execv() which would seem to include localtime_r(). However the fork() man page is not as explicit as I would like (localtime_r isn't signal safe so it is not guaranteed to be safe to call between fork() and execv() but that doesn't mean it will always be a problem either).  You might be able to reproduce the issue by logging between a fork() and execv() but I only saw the crash less than 1 in 10 times that my software ran.  However, the fork() man page is enough to convince me that its not a good idea to call localtime_r() between fork() and execv() and removing the call fixed my issue.

2022-01-15 15:59 UTC, gabime commented
> After a fork() in a multithreaded program, the child can
          safely call only async-signal-safe functions (see
          signal-safety(7)) until such time as it calls execve(2).

spdlog is not async-signal-safe (see #1607), so the crash can be from anywhere, not just localtime.

2022-01-15 16:58 UTC, doug1234 commented
While I agree that spdlog can't make the async-signal-safe guarantee, spdlog is close enough to it (when used carefully) for my purposes minus the spurious call to localtime.  Overall I don't see a down side to this change other than a small increase in complexity and it should improve efficiency in a corner case.

2022-01-15 17:51 UTC, gabime requested changes

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +    , needs_time_(false)
please rename to “need_localtime_”
Some of the flags needs time but not localtime.

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +        needs_time_ = true;
not needed

2022-01-15 17:51 UTC, gabime commented on include/spdlog/pattern_formatter-inl.h
> +    if (needs_time_) {
Please put the open brace in a new line like rest of the codebase

2022-01-16 19:43 UTC, merged

2022-01-16 19:44 UTC, gabime commented
Merged. Thanks @doug1234