added sentry integration
gabime/spdlog pull request #2585
Opened 2022-12-23 14:13 UTC by kirill-nn

created sentry_sink to publish log events with breadcrumb. For now, only DSN is necessary for logger initialization

2022-12-23 15:02 UTC, gabime requested changes
Thanks. Seems to me this better fits to https://github.com/getsentry/sentry-native/tree/master/src/integrations

Have you tried to post the PR their?

2022-12-23 15:02 UTC, gabime commented on include/spdlog/sinks/sentry_sink.h
> +        auto crumb = sentry_value_new_breadcrumb(msg.logger_name.data(), msg.payload.data());
How do the `crumb*` and `location` objects get released ?

2022-12-23 15:02 UTC, gabime commented on include/spdlog/sinks/sentry_sink.h
> +        sentry_init(options);
Shouldn't the be a call to `sentry_options_free(options)` at the end of this function?

2022-12-23 15:02 UTC, gabime commented on include/spdlog/sinks/sentry_sink.h
> +    sentry_sink& operator=(sentry_sink&&) = delete;
Why do you prevent copies?

2022-12-27 16:12 UTC, kirill-nn commented
Thanks, @gabime good points, will be fixed. Not sure about the best repo for PR to be honest.

2022-12-27 16:14 UTC, gabime commented
Please ask in Sentry repo. I am pretty sure they would be happy to get such contribution.

2022-12-27 16:14 UTC, closed without merging