Modify the condition of SPDLOG_CONSTEXPR_FUNC to match that of fmt
gabime/spdlog pull request #2859
Opened 2023-08-18 22:54 UTC by ShujianQian

fix the issue where constexpr function in spdlog may call non-constexpr function in the bundled fmt because FMT_USE_CONSTEXPR is not defined.

fix #2856

2023-08-22 20:36 UTC, gabime requested changes

2023-08-22 20:36 UTC, gabime commented on include/spdlog/common.h
> +#    define __has_feature(x) 0
Please don't define standard macros, even if to 0. It will surely break users code.

2023-08-22 20:39 UTC, gabime commented on include/spdlog/common.h
> +    !defined(__ICL) && !defined(__INTEL_COMPILER) && !defined(__NVCC__)
Can be simplified greatly. No need to check the defined(..), only if comparisons. See https://stackoverflow.com/questions/5085392/what-is-the-value-of-an-undefined-constant-used-in-if

2023-10-11 20:27 UTC, kkraus14 commented
This seemed stale so I have created a new PR based on this PR to try to help it over the finish line: https://github.com/gabime/spdlog/pull/2901

2024-03-21 10:17 UTC, closed without merging